### ISSUE TITLE
The plugin does not work correctly

### ISSUE THREAD

**Issue by hosseinip** [CodeYellowBV/chartist-plugin-legend#18] opened 2016-05-30 12:52 UTC
In the demo version, let say we click on the Piece A legend (red color) in pie chart. However, after clicking on the legend, the piece will not disappear in the chart. The same stays for other pieces as well in some occasions.

In fact, I found the bug and this is what exactly happens:
Let say we have 4 colors for pieces legend. The order of colors is: 1- blue 2- red 3- yellow 4- green. When we unselect the first piece that its color is blue, the plugin resets the colors and again, starts from the first color, blue. As a result, colors of pieces 2 through 4 will be blue, red and yellow while it should be red, yellow and green. In other words, whether a piece is selected or not, the colors should stay the same all the time.

**Comment by SpaceK33z** [comment] 2016-06-10 08:10
Duplicate of #11.

**Closed as completed by SpaceK33z** 2016-06-10 08:10 UTC
